// out_asym_fifo.v

// Generated using ACDS version 20.4 72

`timescale 1 ps / 1 ps
module out_asym_fifo (
		input  wire [1151:0] data,    //  fifo_input.datain
		input  wire          wrreq,   //            .wrreq
		input  wire          rdreq,   //            .rdreq
		input  wire          wrclk,   //            .wrclk
		input  wire          rdclk,   //            .rdclk
		output wire [71:0]   q,       // fifo_output.dataout
		output wire          rdempty, //            .rdempty
		output wire          wrfull   //            .wrfull
	);

	out_asym_fifo_fifo_1910_5vttcmy fifo_0 (
		.data    (data),    //   input,  width = 1152,  fifo_input.datain
		.wrreq   (wrreq),   //   input,     width = 1,            .wrreq
		.rdreq   (rdreq),   //   input,     width = 1,            .rdreq
		.wrclk   (wrclk),   //   input,     width = 1,            .wrclk
		.rdclk   (rdclk),   //   input,     width = 1,            .rdclk
		.q       (q),       //  output,    width = 72, fifo_output.dataout
		.rdempty (rdempty), //  output,     width = 1,            .rdempty
		.wrfull  (wrfull)   //  output,     width = 1,            .wrfull
	);

endmodule
