// tensor_core_accu.v

// Generated using ACDS version 21.4 67

`timescale 1 ps / 1 ps
module tensor_core_accu (
		input  wire        clk,                   //                   clk.clk
		input  wire        clr0,                  //                  clr0.clr
		input  wire        acc_en,                //                acc_en.acc_en
		input  wire        zero_en,               //               zero_en.zero_en
		input  wire [23:0] bf24_a1,               //               bf24_a1.data_in
		input  wire [31:0] cascade_data_in_col_1, // cascade_data_in_col_1.cascade_data_in
		input  wire [23:0] bf24_a2,               //               bf24_a2.data_in
		input  wire [31:0] cascade_data_in_col_2, // cascade_data_in_col_2.cascade_data_in
		input  wire [23:0] bf24_a3,               //               bf24_a3.data_in
		input  wire [31:0] cascade_data_in_col_3, // cascade_data_in_col_3.cascade_data_in
		output wire [23:0] bf24_col_1,            //            bf24_col_1.result_l
		output wire [23:0] bf24_col_2,            //            bf24_col_2.result_l,result_h
		output wire [23:0] bf24_col_3             //            bf24_col_3.result_h
	);

	tensor_core_accu_dsp_prime_10_exjexwi dsp_prime_0 (
		.clk                   (clk),                   //   input,   width = 1,                   clk.clk
		.clr0                  (clr0),                  //   input,   width = 1,                  clr0.clr
		.acc_en                (acc_en),                //   input,   width = 1,                acc_en.acc_en
		.zero_en               (zero_en),               //   input,   width = 1,               zero_en.zero_en
		.bf24_a1               (bf24_a1),               //   input,  width = 24,               bf24_a1.data_in
		.cascade_data_in_col_1 (cascade_data_in_col_1), //   input,  width = 32, cascade_data_in_col_1.cascade_data_in
		.bf24_a2               (bf24_a2),               //   input,  width = 24,               bf24_a2.data_in
		.cascade_data_in_col_2 (cascade_data_in_col_2), //   input,  width = 32, cascade_data_in_col_2.cascade_data_in
		.bf24_a3               (bf24_a3),               //   input,  width = 24,               bf24_a3.data_in
		.cascade_data_in_col_3 (cascade_data_in_col_3), //   input,  width = 32, cascade_data_in_col_3.cascade_data_in
		.bf24_col_1            (bf24_col_1),            //  output,  width = 24,            bf24_col_1.result_l
		.bf24_col_2            (bf24_col_2),            //  output,  width = 24,            bf24_col_2.result_l,result_h
		.bf24_col_3            (bf24_col_3)             //  output,  width = 24,            bf24_col_3.result_h
	);

endmodule
