// in_buffer.v

// Generated using ACDS version 20.4 72

`timescale 1 ps / 1 ps
module in_buffer (
		input  wire [87:0] data,      //      data.datain
		output wire [87:0] q,         //         q.dataout
		input  wire [6:0]  wraddress, // wraddress.wraddress
		input  wire [6:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	in_buffer_ram_2port_2020_um36i7a ram_2port_0 (
		.data      (data),      //   input,  width = 88,      data.datain
		.q         (q),         //  output,  width = 88,         q.dataout
		.wraddress (wraddress), //   input,   width = 7, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 7, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
